import { NextResponse } from "next/server";
import { PrismaNeon } from "@prisma/adapter-neon";
import { neonConfig } from "@neondatabase/serverless";
import { PrismaClient } from "@/src/generated/prisma/client";
import { AuthenticationError, AuthorizationError, TenantAccessError } from "@/src/server/auth/errors";
import { requirePermission } from "@/src/server/auth/permissions";
const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };
function getPrisma(){if(globalForPrisma.prisma)return globalForPrisma.prisma; neonConfig.fetchConnectionCache=true; const connectionString=process.env.DATABASE_URL; if(!connectionString)throw new Error("DATABASE_URL is not configured"); const prisma=new PrismaClient({adapter:new PrismaNeon({connectionString})}); if(process.env.NODE_ENV!=="production")globalForPrisma.prisma=prisma; return prisma;}
function failure(error:unknown,fallback:string){if(error instanceof AuthenticationError)return NextResponse.json({error:error.message},{status:401}); if(error instanceof AuthorizationError||error instanceof TenantAccessError)return NextResponse.json({error:error.message},{status:403}); console.error(fallback,error); return NextResponse.json({error:fallback},{status:500});}
export async function GET(request:Request){try{const context=await requirePermission("course:view"); const params=new URL(request.url).searchParams; const programId=params.get("programId"); const search=params.get("search")?.trim(); const prisma=getPrisma(); const courses=await prisma.course.findMany({where:{tenantId:context.tenantId,status:"ACTIVE",...(programId?{programId}:{}),...(search?{OR:[{name:{contains:search,mode:"insensitive"}},{code:{contains:search,mode:"insensitive"}}]}:{})},orderBy:[{displayOrder:"asc"},{name:"asc"}],include:{program:{select:{id:true,name:true,code:true,department:{select:{id:true,name:true,code:true}}}}}}); return NextResponse.json({courses});}catch(error){return failure(error,"Unable to load courses. Please try again.");}}
export async function POST(request:Request){try{const context=await requirePermission("course:create"); const body=(await request.json()) as Record<string,unknown>; const programId=typeof body.programId==="string"?body.programId:""; const name=typeof body.name==="string"?body.name.trim():""; const code=typeof body.code==="string"?body.code.trim().toUpperCase():""; const description=typeof body.description==="string"?body.description.trim()||null:null; const type=typeof body.type==="string"&&["ELECTIVE","PRACTICAL","PROJECT","OTHER"].includes(body.type)?body.type:"CORE"; const credits=typeof body.credits==="number"&&Number.isInteger(body.credits)&&body.credits>0?body.credits:null; const weeklyHours=typeof body.weeklyHours==="number"&&Number.isInteger(body.weeklyHours)&&body.weeklyHours>0?body.weeklyHours:null; if(!programId)return NextResponse.json({error:"Select a program."},{status:400}); if(!name)return NextResponse.json({error:"Enter a course name."},{status:400}); if(!code)return NextResponse.json({error:"Enter a course code."},{status:400}); const prisma=getPrisma(); const program=await prisma.program.findFirst({where:{id:programId,tenantId:context.tenantId,status:"ACTIVE"},select:{id:true}}); if(!program)return NextResponse.json({error:"Select an active program."},{status:400}); const duplicate=await prisma.course.findUnique({where:{tenantId_code:{tenantId:context.tenantId,code}},select:{id:true}}); if(duplicate)return NextResponse.json({error:"A course with this code already exists."},{status:409}); const course=await prisma.course.create({data:{tenantId:context.tenantId,programId,name,code,description,type,credits,weeklyHours},include:{program:{select:{id:true,name:true,code:true,department:{select:{id:true,name:true,code:true}}}}}}); return NextResponse.json({course},{status:201});}catch(error){return failure(error,"Unable to create the course. Please try again.");}}
