import { NextResponse } from "next/server";
import { PrismaNeon } from "@prisma/adapter-neon";
import { neonConfig } from "@neondatabase/serverless";
import { PrismaClient } from "@/src/generated/prisma/client";
import { AuthenticationError, AuthorizationError, TenantAccessError } from "@/src/server/auth/errors";
import { requirePermission } from "@/src/server/auth/permissions";

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };
function getPrisma(){if(globalForPrisma.prisma)return globalForPrisma.prisma;neonConfig.fetchConnectionCache=true;const connectionString=process.env.DATABASE_URL;if(!connectionString)throw new Error("DATABASE_URL is not configured");const prisma=new PrismaClient({adapter:new PrismaNeon({connectionString})});if(process.env.NODE_ENV!=="production")globalForPrisma.prisma=prisma;return prisma;}
function failure(error:unknown,fallback:string){if(error instanceof AuthenticationError)return NextResponse.json({error:error.message},{status:401});if(error instanceof AuthorizationError||error instanceof TenantAccessError)return NextResponse.json({error:error.message},{status:403});console.error(fallback,error);return NextResponse.json({error:fallback},{status:500});}
const statuses=["ACTIVE","INACTIVE","ON_LEAVE","ARCHIVED"] as const;
const types=["TEACHING","NON_TEACHING"] as const;
const optional=(body:Record<string,unknown>,key:string)=>typeof body[key]==="string"?String(body[key]).trim()||null:null;
const validDate=(value:string|null)=>value?new Date(value):null;

export async function GET(request:Request){try{const context=await requirePermission("staff:view");const url=new URL(request.url);const page=Math.max(1,Number(url.searchParams.get("page")??1));const pageSize=Math.min(100,Math.max(1,Number(url.searchParams.get("pageSize")??10)));const search=url.searchParams.get("search")?.trim();const staffType=url.searchParams.get("staffType");const departmentId=url.searchParams.get("departmentId");const status=url.searchParams.get("status");const where={tenantId:context.tenantId,...(status&&statuses.includes(status as typeof statuses[number])?{status:status as typeof statuses[number]}:{}),...(staffType&&types.includes(staffType as typeof types[number])?{staffType:staffType as typeof types[number]}:{}),...(departmentId?{departmentId}:{}),...(search?{OR:[{firstName:{contains:search,mode:"insensitive" as const}},{lastName:{contains:search,mode:"insensitive" as const}},{employeeNumber:{contains:search,mode:"insensitive" as const}},{email:{contains:search,mode:"insensitive" as const}},{designation:{contains:search,mode:"insensitive" as const}}]}:{})};const prisma=getPrisma();const [staff,total,all,byType]=await Promise.all([prisma.staffMember.findMany({where,orderBy:[{lastName:"asc"},{firstName:"asc"}],skip:(page-1)*pageSize,take:pageSize,include:{department:{select:{id:true,name:true}}}}),prisma.staffMember.count({where}),prisma.staffMember.count({where:{tenantId:context.tenantId,status:"ACTIVE"}}),prisma.staffMember.groupBy({by:["staffType"],where:{tenantId:context.tenantId,status:"ACTIVE"},_count:{_all:true}})]);return NextResponse.json({staff,pagination:{page,pageSize,total,totalPages:Math.max(1,Math.ceil(total/pageSize))},stats:{total:all,teaching:byType.find(x=>x.staffType==="TEACHING")?._count._all??0,nonTeaching:byType.find(x=>x.staffType==="NON_TEACHING")?._count._all??0}});}catch(error){return failure(error,"Unable to load faculty and staff.");}}

export async function POST(request:Request){try{const context=await requirePermission("staff:create");const body=(await request.json()) as Record<string,unknown>;const employeeNumber=typeof body.employeeNumber==="string"?body.employeeNumber.trim().toUpperCase():"";const firstName=typeof body.firstName==="string"?body.firstName.trim():"";const lastName=typeof body.lastName==="string"?body.lastName.trim():"";const designation=typeof body.designation==="string"?body.designation.trim():"";const employmentType=typeof body.employmentType==="string"?body.employmentType.trim():"";const staffType=typeof body.staffType==="string"?body.staffType:"";const joiningDate=validDate(typeof body.joiningDate==="string"?body.joiningDate:null);const departmentId=optional(body,"departmentId");const photoUrl=optional(body,"photoUrl");if(!employeeNumber||!firstName||!lastName||!designation||!employmentType||!types.includes(staffType as typeof types[number])||!joiningDate)return NextResponse.json({error:"Complete all required staff details."},{status:400});if(Number.isNaN(joiningDate.getTime()))return NextResponse.json({error:"Enter a valid joining date."},{status:400});if(photoUrl&&(!photoUrl.startsWith("data:image/")||photoUrl.length>3_000_000))return NextResponse.json({error:"Staff photo must be a valid image up to 2MB."},{status:400});const prisma=getPrisma();const [duplicate,department]=await Promise.all([prisma.staffMember.findUnique({where:{tenantId_employeeNumber:{tenantId:context.tenantId,employeeNumber}},select:{id:true}}),departmentId?prisma.department.findFirst({where:{id:departmentId,tenantId:context.tenantId,status:"ACTIVE"},select:{id:true}}):Promise.resolve(null)]);if(duplicate)return NextResponse.json({error:"A staff member with this employee ID already exists."},{status:409});if(departmentId&&!department)return NextResponse.json({error:"Select an active department."},{status:400});const dateOfBirth=validDate(typeof body.dateOfBirth==="string"?body.dateOfBirth:null);if(dateOfBirth&&Number.isNaN(dateOfBirth.getTime()))return NextResponse.json({error:"Enter a valid date of birth."},{status:400});const staff=await prisma.staffMember.create({data:{tenantId:context.tenantId,employeeNumber,firstName,lastName,email:optional(body,"email"),phone:optional(body,"phone"),photoUrl,dateOfBirth,gender:optional(body,"gender"),address:optional(body,"address"),staffType:staffType as typeof types[number],designation,departmentId,employmentType,joiningDate,roleName:optional(body,"roleName"),accessLevel:optional(body,"accessLevel"),status:(statuses.includes(body.status as typeof statuses[number])?body.status:"ACTIVE") as typeof statuses[number]},include:{department:{select:{id:true,name:true}}}});return NextResponse.json({staff},{status:201});}catch(error){return failure(error,"Unable to create the staff member.");}}
