"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ApartmentOutlined, CheckCircleOutlined, InfoCircleOutlined, LoadingOutlined, SaveOutlined } from "@ant-design/icons";
import { Alert, Button, Card, Empty, Skeleton, Tag } from "antd";
import styles from "../institution.module.css";
import { ApplicationShell } from "@/components/application-shell";
import { InstitutionNavigation } from "@/components/institution/institution-navigation";

type InstitutionType = { id:string; code:string; name:string; description:string|null; capabilities:Array<{enabled:boolean;capability:{id:string;name:string}}> };

export default function InstitutionTypePage(){
 const [types,setTypes]=useState<InstitutionType[]>([]); const [current,setCurrent]=useState<InstitutionType|null>(null); const [selectedId,setSelectedId]=useState(""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<{kind:"success"|"error"|"info";text:string}|null>(null);
 useEffect(()=>{let cancelled=false; async function load(){try{const [a,b]=await Promise.all([fetch("/api/platform/institution-types",{cache:"no-store"}),fetch("/api/institution/type",{cache:"no-store"})]);const typesData=await a.json();const currentData=await b.json();if(!a.ok)throw new Error(typesData.error??"Unable to load institution types.");if(!b.ok)throw new Error(currentData.error??"Unable to load the current institution type.");if(cancelled)return;setTypes(typesData.institutionTypes);setCurrent(currentData.institutionType);setSelectedId(currentData.institutionType?.id??"");}catch(error){if(!cancelled)setMessage({kind:"error",text:error instanceof Error?error.message:"We couldn't load the institution type. Please try again."});}finally{if(!cancelled)setLoading(false);}} void load();return()=>{cancelled=true};},[]);
 async function save(){if(!selectedId||selectedId===current?.id)return;const selected=types.find(x=>x.id===selectedId);if(!selected)return;if(!window.confirm("Changing the institution type may change which features are available. Existing records will not be deleted. Continue?"))return;setSaving(true);setMessage(null);try{const r=await fetch("/api/institution/type",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({institutionTypeId:selectedId})});const data=await r.json();if(!r.ok)throw new Error(data.error??"We couldn't update the institution type. Please try again.");setCurrent(data.institutionType);setMessage({kind:"success",text:"Institution type updated successfully."});}catch(error){setMessage({kind:"error",text:error instanceof Error?error.message:"We couldn't update the institution type. Please try again."});}finally{setSaving(false);}}
 const selected=types.find(x=>x.id===selectedId);const enabled=selected?.capabilities.filter(x=>x.enabled)??[];
 return <ApplicationShell pageTitle="Institution type" pageContext="Choose the category that best describes your institution" selectedKey="institution"><div className={styles.typePage}>
  <div className={styles.breadcrumb}><Link href="/">Home</Link><span>/</span><Link href="/institution">Institution</Link><span>/</span><strong>Institution type</strong></div>
  <section className={styles.typeHero}><span className={styles.typeHeroIcon}><ApartmentOutlined/></span><div><span className={styles.overline}>INSTITUTION SETUP</span><h1>Choose your institution type</h1><p>Select the category that best describes your institution. This helps EduInstitution prepare the right features for your workspace.</p></div></section>
  <InstitutionNavigation/>
  {message?<Alert className={`${styles.inlineAlert} ${message.kind==="success"?"feedback-success":message.kind==="error"?"feedback-error":"feedback-info"}`} type={message.kind==="error"?"error":message.kind==="success"?"success":"info"} message={message.text} showIcon closable onClose={()=>setMessage(null)}/>:null}
  <Card className={styles.typeCard} styles={{body:{padding:24}}}>{loading?<div className={styles.loading}><Skeleton active paragraph={{rows:6}}/><span><LoadingOutlined/> Loading your institution setup...</span></div>:types.length===0?<div className={styles.empty}><Empty description="No institution types are available right now."/><p>Please try again later.</p></div>:<>
   <div className={styles.typeCardHeading}><div><h2>Institution category</h2><p>Choose one option from the list below.</p></div><Tag className={styles.currentTag}><CheckCircleOutlined/> {current?.name??"Not selected"}</Tag></div>
   <label htmlFor="institution-type" className={styles.fieldLabel}>Institution type</label><select id="institution-type" value={selectedId} onChange={e=>setSelectedId(e.target.value)} className={styles.select}><option value="">Select an institution type</option>{types.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
   <div className={styles.exampleHint}><InfoCircleOutlined/><span><strong>Example:</strong> A university can select “University” so relevant academic features can be prepared for its workspace.</span></div>
   {selected?<div className={styles.selectedPreview}><span className={styles.selectedIcon}><ApartmentOutlined/></span><div><span>SELECTED TYPE</span><h3>{selected.name}</h3><p>{selected.description??"This institution type helps determine which features are available to your workspace."}</p>{enabled.length>0?<div className={styles.capabilities}><strong>Available features</strong><div>{enabled.slice(0,6).map(x=><Tag key={x.capability.id}>{x.capability.name}</Tag>)}</div></div>:null}</div></div>:null}
   <div className={styles.changeNote}><InfoCircleOutlined/><div><strong>What changes when you switch?</strong><p>The selected type controls which platform features are available. Existing records are not deleted when you change this setting.</p></div></div>
   <div className={styles.saveBar}><span>{selectedId&&selectedId!==current?.id?"You have unsaved changes":"Your institution type is up to date"}</span><Button type="primary" icon={<SaveOutlined/>} onClick={()=>void save()} loading={saving} disabled={!selectedId||selectedId===current?.id}>Save changes</Button></div>
  </>}</Card>
 </div></ApplicationShell>;
}
