"use client";
import { useCallback,useEffect,useMemo,useState,type ReactNode } from "react";
import Link from "next/link";
import { Avatar,Button,Input,Modal,Pagination,Select,Spin,notification } from "antd";
import { EditOutlined,FilterOutlined,PlusOutlined,ReadOutlined,SearchOutlined,TeamOutlined,UserOutlined } from "@ant-design/icons";
import { ApplicationShell } from "@/components/application-shell";
type AcademicYear={id:string;name:string;status:string}; type Department={id:string;name:string;status:string}; type Program={id:string;name:string;department:{id:string;name:string};status:string}; type Enrollment={academicYear:{id:string;name:string};department:{id:string;name:string};program:{id:string;name:string}}; type Student={id:string;studentNumber:string;firstName:string;lastName:string;email:string|null;phone:string|null;photoUrl:string|null;status:string;enrollments:Enrollment[]};
export default function StudentsPage(){const[api,holder]=notification.useNotification();const[students,setStudents]=useState<Student[]>([]);const[years,setYears]=useState<AcademicYear[]>([]);const[departments,setDepartments]=useState<Department[]>([]);const[programs,setPrograms]=useState<Program[]>([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState("");const[academicYearId,setAcademicYearId]=useState("");const[departmentId,setDepartmentId]=useState("");const[programId,setProgramId]=useState("");const[status,setStatus]=useState("ACTIVE");const[page,setPage]=useState(1);const[pageSize,setPageSize]=useState(10);const[total,setTotal]=useState(0);const notify=useCallback((type:"success"|"error"|"warning"|"info",message:string)=>api[type]({message,placement:"bottomRight",className:`edu-notification edu-notification-${type}`}),[api]);
useEffect(()=>{const raw=sessionStorage.getItem("edu-student-flash");if(!raw)return;sessionStorage.removeItem("edu-student-flash");try{const flash=JSON.parse(raw) as {type:"success"|"error"|"warning"|"info";message:string};api[flash.type]({message:flash.message,placement:"bottomRight",className:`edu-notification edu-notification-${flash.type}`});}catch{/* ignore malformed flash data */}},[api]);
useEffect(()=>{const raw=sessionStorage.getItem("edu-student-flash");if(!raw)return;sessionStorage.removeItem("edu-student-flash");try{const flash=JSON.parse(raw) as {type:"success"|"error"|"warning"|"info";message:string};api[flash.type]({message:flash.message,placement:"bottomRight",className:`edu-notification edu-notification-${flash.type}`});}catch{/* ignore malformed flash data */}},[api]);
const query=useCallback(()=>{const p=new URLSearchParams({page:String(page),pageSize:String(pageSize),status});if(search.trim())p.set("search",search.trim());if(academicYearId)p.set("academicYearId",academicYearId);if(departmentId)p.set("departmentId",departmentId);if(programId)p.set("programId",programId);return p;},[page,pageSize,status,search,academicYearId,departmentId,programId]);
const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`/api/students?${query()}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error??"We couldn't load students.");setStudents(d.students??[]);setTotal(d.pagination?.total??0);}catch(e){notify("error",e instanceof Error?e.message:"We couldn't load students.");}finally{setLoading(false);}},[query,notify]);
useEffect(()=>{let cancelled=false;const params=query();void fetch(`/api/students?${params}`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error??"We couldn\'t load students.");return d;}).then(d=>{if(!cancelled){setStudents(d.students??[]);setTotal(d.pagination?.total??0);setLoading(false);}}).catch((e:unknown)=>{if(!cancelled){notify("error",e instanceof Error?e.message:"We couldn\'t load students.");setLoading(false);}});return()=>{cancelled=true;};},[query,notify]);useEffect(()=>{let c=false;void Promise.all([fetch("/api/academic/years"),fetch("/api/academic/departments"),fetch("/api/academic/programs")]).then(async rs=>{const d=await Promise.all(rs.map(r=>r.json()));if(c)return;setYears((d[0].academicYears??[]).filter((x:AcademicYear)=>x.status==="ACTIVE"));setDepartments((d[1].departments??[]).filter((x:Department)=>x.status==="ACTIVE"));setPrograms((d[2].programs??[]).filter((x:Program)=>x.status!=="ARCHIVED"));}).catch(()=>!c&&notify("error","Unable to load student filters."));return()=>{c=true;};},[notify]);
const visiblePrograms=useMemo(()=>programs.filter(x=>!departmentId||x.department.id===departmentId),[programs,departmentId]);
function archiveStudent(s:Student){Modal.confirm({title:"Archive student?",content:`${s.firstName} ${s.lastName} will be removed from active student management.`,okText:"Archive",okButtonProps:{danger:true},onOk:async()=>{try{const r=await fetch(`/api/students/${s.id}`,{method:"DELETE"});const d=await r.json();if(!r.ok)throw new Error(d.error??"We couldn't archive the student.");notify("success","Student archived successfully.");await load();}catch(e){notify("error",e instanceof Error?e.message:"We couldn't archive the student.");}}});}
return <ApplicationShell selectedKey="students" showPageContext={false}>{holder}<div className="students-page">
<header className="students-hero"><div><div className="students-title-row"><div className="students-title-icon"><UserOutlined/></div><div><h1>Students</h1><p>Manage student information, profile, admission, and academic details.</p></div></div></div><div className="students-actions"><Link href="/students/new"><Button type="primary" icon={<PlusOutlined/>}>Add student</Button></Link></div></header>
<section className="students-stats"><Stat label="Total Students" value={total} tone="green" icon={<TeamOutlined/>}/><Stat label="Active Students" value={status==="ACTIVE"?total:"—"} tone="blue" icon={<UserOutlined/>}/><Stat label="New Admissions" value="—" tone="orange" icon={<ReadOutlined/>}/><Stat label="Alumni" value="—" tone="purple" icon={<TeamOutlined/>}/></section>
<section className="students-filters"><Input allowClear value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} prefix={<SearchOutlined/>} placeholder="Search by name, roll number, or email..."/><Select value={academicYearId||undefined} allowClear placeholder="Academic Year" onChange={v=>{setAcademicYearId(v??"");setPage(1);}} options={years.map(x=>({value:x.id,label:x.name}))}/><Select value={programId||undefined} allowClear placeholder="Program" onChange={v=>{setProgramId(v??"");setPage(1);}} options={visiblePrograms.map(x=>({value:x.id,label:x.name}))}/><Select value={departmentId||undefined} allowClear placeholder="Department" onChange={v=>{setDepartmentId(v??"");setProgramId("");setPage(1);}} options={departments.map(x=>({value:x.id,label:x.name}))}/><Select value={status} onChange={v=>{setStatus(v);setPage(1);}} options={[{value:"ACTIVE",label:"Active"},{value:"ARCHIVED",label:"Archived"}]}/><Button icon={<FilterOutlined/>}>Filter</Button></section>
<section className="students-table-card">{loading?<div className="students-loading"><Spin size="large"/></div>:<><div className="students-table-wrap"><table className="students-table"><thead><tr><th>Student</th><th>Roll Number</th><th>Program</th><th>Department</th><th>Academic Year</th><th>Status</th><th>Actions</th></tr></thead><tbody>{students.map(s=>{const e=s.enrollments[0];return <tr key={s.id}><td><div className="student-cell"><Avatar size={42} src={s.photoUrl||undefined} icon={!s.photoUrl?<UserOutlined/>:undefined}/><div><strong>{s.firstName} {s.lastName}</strong><span>{s.email??"No email"}</span></div></div></td><td>{s.studentNumber}</td><td>{e?.program.name??"—"}</td><td>{e?.department.name??"—"}</td><td>{e?.academicYear.name??"—"}</td><td><span className={s.status==="ACTIVE"?"student-status active":"student-status archived"}>{s.status==="ACTIVE"?"Active":"Archived"}</span></td><td><div className="student-row-actions"><Link href={`/students/${s.id}/edit`}><Button icon={<EditOutlined/>} aria-label="Edit student"/></Link><Button danger onClick={()=>archiveStudent(s)}>Archive</Button></div></td></tr>;})}</tbody></table></div><div className="students-pagination"><span>Showing {total?((page-1)*pageSize)+1:0} to {Math.min(page*pageSize,total)} of {total} students</span><Pagination current={page} pageSize={pageSize} total={total} showSizeChanger pageSizeOptions={[10,20,50,100]} onChange={(p,ps)=>{setPage(ps!==pageSize?1:p);setPageSize(ps);}}/></div></>}</section>
</div></ApplicationShell>}
function Stat({label,value,tone,icon}:{label:string;value:string|number;tone:string;icon:ReactNode}){return <div className="students-stat"><div className={`students-stat-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}
